// This file is auto-generated by scripts/sync_docs.py.
// Do not edit it manually.

export const courseSidebar = [
  {
    text: "Course Home",
    link: "/",
  },
  {
    text: "Getting Started",
    link: "/#getting-started",
    items: [
      {
        text: "What is Python?",
        link: "/#what-is-python",
      },
      {
        text: "Why learn Python?",
        link: "/#why-learn-python",
        items: [
          {
            text: "1. The Language of AI and the Future",
            link: "/#1-the-language-of-ai-and-the-future",
          },
          {
            text: "2. Web Development Powerhouse",
            link: "/#2-web-development-powerhouse",
          },
          {
            text: "3. Easy to learn, powerful to master",
            link: "/#3-easy-to-learn-powerful-to-master",
          },
          {
            text: "4. Huge Ecosystem",
            link: "/#4-huge-ecosystem",
          },
          {
            text: "5. Career opportunities",
            link: "/#5-career-opportunities",
          },
        ],
      },
      {
        text: "Installation and Setup",
        link: "/#installation-and-setup",
        items: [
          {
            text: "Download",
            link: "/#download",
          },
          {
            text: "Installation",
            link: "/#installation",
          },
          {
            text: "VS Code",
            link: "/#vs-code",
          },
          {
            text: "Extension",
            link: "/#extension",
          },
        ],
      },
    ],
    collapsed: false,
  },
  {
    text: "Chapter I: Core Python",
    link: "/#chapter-i-core-python",
    items: [
      {
        text: "Hello World",
        link: "/#hello-world",
        items: [
          {
            text: "Structure of a Python program",
            link: "/#structure-of-a-python-program",
          },
        ],
      },
      {
        text: "Variables",
        link: "/#variables",
      },
      {
        text: "Built-in Data Types",
        link: "/#built-in-data-types",
        items: [
          {
            text: "int",
            link: "/#int",
          },
          {
            text: "float",
            link: "/#float",
          },
          {
            text: "complex",
            link: "/#complex",
          },
          {
            text: "str (String)",
            link: "/#str-string",
          },
          {
            text: "bool",
            link: "/#bool",
          },
          {
            text: "None",
            link: "/#none",
          },
        ],
      },
      {
        text: "Data Structures",
        link: "/#data-structures",
        items: [
          {
            text: "Lists",
            link: "/#lists",
          },
          {
            text: "Tuples",
            link: "/#tuples",
          },
          {
            text: "Dictionaries",
            link: "/#dictionaries",
          },
          {
            text: "Sets",
            link: "/#sets",
          },
        ],
      },
      {
        text: "Type Conversion",
        link: "/#type-conversion",
      },
      {
        text: "Operators",
        link: "/#operators",
        items: [
          {
            text: "Arithmetic Operators",
            link: "/#arithmetic-operators",
          },
          {
            text: "Comparison Operators",
            link: "/#comparison-operators",
          },
          {
            text: "Logical Operators",
            link: "/#logical-operators",
          },
          {
            text: "Assignment Operators",
            link: "/#assignment-operators",
          },
          {
            text: "Membership Operators",
            link: "/#membership-operators",
          },
          {
            text: "Operator Precedence",
            link: "/#operator-precedence",
          },
        ],
      },
      {
        text: "Falsy Values",
        link: "/#falsy-values",
      },
      {
        text: "String Formatting",
        link: "/#string-formatting",
      },
      {
        text: "Flow Control",
        link: "/#flow-control",
        items: [
          {
            text: "If/Else",
            link: "/#ifelse",
          },
          {
            text: "Match/Case (Python 3.10+)",
            link: "/#matchcase-python-310",
          },
          {
            text: "Loops",
            link: "/#loops",
          },
        ],
      },
      {
        text: "Functions",
        link: "/#functions",
        items: [
          {
            text: "Simple declaration",
            link: "/#simple-declaration",
          },
          {
            text: "Parameters and arguments",
            link: "/#parameters-and-arguments",
          },
          {
            text: "Default arguments",
            link: "/#default-arguments",
          },
          {
            text: "Keyword arguments",
            link: "/#keyword-arguments",
          },
          {
            text: "Variable arguments (args and kwargs)",
            link: "/#variable-arguments-args-and-kwargs",
          },
          {
            text: "Return values",
            link: "/#return-values",
          },
          {
            text: "Lambda functions",
            link: "/#lambda-functions",
          },
          {
            text: "Docstrings",
            link: "/#docstrings",
          },
        ],
      },
      {
        text: "Modules",
        link: "/#modules",
        items: [
          {
            text: "What are modules?",
            link: "/#what-are-modules",
          },
          {
            text: "Creating a module",
            link: "/#creating-a-module",
          },
          {
            text: "Importing modules",
            link: "/#importing-modules",
          },
          {
            text: "The name variable",
            link: "/#the-name-variable",
          },
          {
            text: "Standard library modules",
            link: "/#standard-library-modules",
          },
        ],
      },
      {
        text: "Packages",
        link: "/#packages",
        items: [
          {
            text: "What are packages?",
            link: "/#what-are-packages",
          },
          {
            text: "Creating a package",
            link: "/#creating-a-package",
          },
          {
            text: "Using a package",
            link: "/#using-a-package",
          },
        ],
      },
      {
        text: "Virtual Environments",
        link: "/#virtual-environments",
        items: [
          {
            text: "What are virtual environments?",
            link: "/#what-are-virtual-environments",
          },
          {
            text: "Creating a virtual environment",
            link: "/#creating-a-virtual-environment",
          },
          {
            text: "Activating",
            link: "/#activating",
          },
          {
            text: "Deactivating",
            link: "/#deactivating",
          },
          {
            text: "Managing dependencies",
            link: "/#managing-dependencies",
          },
        ],
      },
      {
        text: "Useful Commands",
        link: "/#useful-commands",
        items: [
          {
            text: "Running scripts",
            link: "/#running-scripts",
          },
          {
            text: "Virtual environments",
            link: "/#virtual-environments-1",
          },
          {
            text: "Package management",
            link: "/#package-management",
          },
          {
            text: "Code formatting and linting",
            link: "/#code-formatting-and-linting",
          },
        ],
      },
      {
        text: "Build & Packaging",
        link: "/#build--packaging",
        items: [
          {
            text: "The pyproject.toml file",
            link: "/#the-pyprojecttoml-file",
          },
          {
            text: "Building packages",
            link: "/#building-packages",
          },
          {
            text: "Project structure",
            link: "/#project-structure",
          },
        ],
      },
    ],
    collapsed: false,
  },
  {
    text: "Chapter II: Advanced Features",
    link: "/#chapter-ii-advanced-features",
    items: [
      {
        text: "List Comprehensions",
        link: "/#list-comprehensions",
        items: [
          {
            text: "Basic syntax",
            link: "/#basic-syntax",
          },
          {
            text: "With condition",
            link: "/#with-condition",
          },
          {
            text: "With conditional expression",
            link: "/#with-conditional-expression",
          },
          {
            text: "Nested comprehensions",
            link: "/#nested-comprehensions",
          },
          {
            text: "Set and dict comprehensions",
            link: "/#set-and-dict-comprehensions",
          },
        ],
      },
      {
        text: "Type Hints",
        link: "/#type-hints",
        items: [
          {
            text: "Basic type hints",
            link: "/#basic-type-hints",
          },
          {
            text: "Union types (Python 3.10+)",
            link: "/#union-types-python-310",
          },
          {
            text: "Optional types",
            link: "/#optional-types",
          },
          {
            text: "TypedDict",
            link: "/#typeddict",
          },
          {
            text: "Generics (Python 3.12+)",
            link: "/#generics-python-312",
          },
        ],
      },
      {
        text: "Classes & Magic Methods",
        link: "/#classes--magic-methods",
        items: [
          {
            text: "Defining a class",
            link: "/#defining-a-class",
          },
          {
            text: "Magic methods",
            link: "/#magic-methods",
          },
          {
            text: "Data classes (Python 3.7+)",
            link: "/#data-classes-python-37",
          },
        ],
      },
      {
        text: "Errors and Exceptions",
        link: "/#errors-and-exceptions",
        items: [
          {
            text: "Try-Except",
            link: "/#try-except",
          },
          {
            text: "Raising exceptions",
            link: "/#raising-exceptions",
          },
          {
            text: "Custom exceptions",
            link: "/#custom-exceptions",
          },
        ],
      },
      {
        text: "Iterators & Generators",
        link: "/#iterators--generators",
        items: [
          {
            text: "Iterators",
            link: "/#iterators",
          },
          {
            text: "Generators",
            link: "/#generators",
          },
          {
            text: "Generator expressions",
            link: "/#generator-expressions",
          },
          {
            text: "Reading large files",
            link: "/#reading-large-files",
          },
        ],
      },
      {
        text: "Decorators",
        link: "/#decorators",
        items: [
          {
            text: "Basic decorator",
            link: "/#basic-decorator",
          },
          {
            text: "Decorators with arguments",
            link: "/#decorators-with-arguments",
          },
          {
            text: "Authentication decorator",
            link: "/#authentication-decorator",
          },
        ],
      },
      {
        text: "Context Managers",
        link: "/#context-managers",
        items: [
          {
            text: "Using context managers",
            link: "/#using-context-managers",
          },
          {
            text: "Custom context manager",
            link: "/#custom-context-manager",
          },
          {
            text: "Function-based context manager",
            link: "/#function-based-context-manager",
          },
        ],
      },
      {
        text: "Pattern Matching (Python 3.10+)",
        link: "/#pattern-matching-python-310",
        items: [
          {
            text: "Matching with guards",
            link: "/#matching-with-guards",
          },
          {
            text: "Matching classes",
            link: "/#matching-classes",
          },
          {
            text: "Matching JSON-like data",
            link: "/#matching-json-like-data",
          },
        ],
      },
    ],
    collapsed: false,
  },
  {
    text: "Chapter III: Concurrency",
    link: "/#chapter-iii-concurrency",
    items: [
      {
        text: "The GIL (Global Interpreter Lock)",
        link: "/#the-gil-global-interpreter-lock",
      },
      {
        text: "Threading (for I/O-bound tasks)",
        link: "/#threading-for-io-bound-tasks",
        items: [
          {
            text: "Thread pool",
            link: "/#thread-pool",
          },
        ],
      },
      {
        text: "Async/Await",
        link: "/#asyncawait",
        items: [
          {
            text: "Basic async example",
            link: "/#basic-async-example",
          },
          {
            text: "Running multiple tasks",
            link: "/#running-multiple-tasks",
          },
          {
            text: "Async HTTP requests",
            link: "/#async-http-requests",
          },
          {
            text: "Async vs Threads",
            link: "/#async-vs-threads",
          },
        ],
      },
      {
        text: "Multiprocessing (for CPU-bound work)",
        link: "/#multiprocessing-for-cpu-bound-work",
        items: [
          {
            text: "Sharing data between processes",
            link: "/#sharing-data-between-processes",
          },
        ],
      },
      {
        text: "Free-Threading (Python 3.13+)",
        link: "/#free-threading-python-313",
      },
      {
        text: "Decision Matrix for 2026",
        link: "/#decision-matrix-for-2026",
      },
    ],
    collapsed: false,
  },
  {
    text: "Appendix",
    link: "/#appendix",
    items: [
      {
        text: "Next Steps (AI & Web)",
        link: "/#next-steps-ai--web",
        items: [
          {
            text: "Web Development",
            link: "/#web-development",
          },
          {
            text: "AI & Data Science",
            link: "/#ai--data-science",
          },
        ],
      },
    ],
    collapsed: false,
  },
  {
    text: "Support",
    link: "/#support",
  },
  {
    text: "Contribution",
    link: "/#contribution",
  },
  {
    text: "Project References",
    link: "/#project-references",
  },
]

export const contributionSidebar = [
  {
    text: "Contribution",
    link: "/contribution/",
  },
  {
    text: "Course Home",
    link: "/",
  },
]
